apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -c
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: alertmanager
  name: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: alertmanager
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -c
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: alertmanager
    spec:
      containers:
        - args:
            - --config.file=/etc/alertmanager/alertmanager.yml
          image: prom/alertmanager:latest
          name: alertmanager
          ports:
            - containerPort: 9093
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/alertmanager/alertmanager.yml
              name: alertmanager-cm0
              readOnly: true
              subPath: alertmanager.yml
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: alertmanager.yml
                path: alertmanager.yml
            name: alertmanager-cm0
          name: alertmanager-cm0
