apiVersion: v1
data:
  alertmanager.yml: |-
    global:
      resolve_timeout: 5m
    receivers:
      - name: "email"
        # email_configs:
        # - auth_password: {{ .Values.mail.pass }}
        #   auth_username: {{ .Values.mail.user }}
        #   auth_identity: {{ .Values.mail.user }}
        #   from: {{ .Values.mail.user }}
        #   smarthost: {{ .Values.mail.host }}:{{ .Values.mail.port }}
        #   to: {{ .Values.mail.user }}
    route:
      group_by: ["alertname"]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: "email"
      routes:
      - match:
          alertname: HighMemoryUsage
          receiver: "email"
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: alertmanager
  name: alertmanager-cm0
