apiVersion: v1
data:
  nginx.conf: "events {}\nhttp {\n    server {\n        listen 80;\n \n        location / {\n            proxy_pass http://silly-demo:8080;\n        }\n    }\n}\n"
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: nginx
  name: nginx-cm0
