apiVersion: v1
data:
  alerts.yml: |
    groups:
    - name: memory-alerts
      rules:
      - alert: HighMemoryUsage
        annotations:
          description: Memory usage is above 128MB.
          summary: Memory usage is above 128MB
        expr: (node_memory_MemTotal_bytes - node_memory_MemFree_bytes) > 128 * 1024 * 1024
        for: 1m
        labels:
          severity: critical
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: prometheus
  name: prometheus-cm1
