apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -c
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: silly-demo
  name: silly-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: silly-demo
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -c
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: silly-demo
    spec:
      containers:
        - env:
            - name: DB_ENDPOINT
              value: postgres
            - name: DB_NAME
              value: db
            - name: DB_PASS
              value: ohiorizz
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: PGPASSWORD
              value: ohiorizz
          image: tabatskyi/silly_demo:latest
          name: silly-demo
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /app
              name: silly-demo-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: silly-demo-cm0
          name: silly-demo-cm0
