services:
  silly-demo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - DB_ENDPOINT=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=ohiorizz
      - PGPASSWORD=ohiorizz
      - DB_NAME=db
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ohiorizz
      POSTGRES_DB: silly_demo_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
