apiVersion: v1
kind: Service
metadata:
  name: silly-demo
spec:
  type: {{ .Values.service.sillyDemo.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.sillyDemo.port }}
      targetPort: {{ .Values.service.sillyDemo.port }}
  selector:
    app: silly-demo
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: {{ .Values.service.nginx.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.nginx.port }}
      targetPort: {{ .Values.service.nginx.port }}
  selector:
    app: silly-demo
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: {{ .Values.service.postgres.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.postgres.port }}
      targetPort: {{ .Values.service.postgres.port }}
  selector:
    app: postgres
